export type LayoutArchetype = {
  id: string;
  name: string;
  purpose: string;
  bestFor: string[];
  regions: string[];
  mobileTransformation: string[];
  completionSignal: string;
};

export const layoutArchetypes: LayoutArchetype[] = [
  { id: "marketing", name: "Marketing", purpose: "Move from a clear proposition to credible evidence and one primary conversion action.", bestFor: ["Product launches", "Service explanations", "Campaign landing pages"], regions: ["Orientation and primary navigation", "Proposition and primary action", "Evidence or proof", "How it works or feature explanation", "Objection handling", "Closing action"], mobileTransformation: ["Preserve proposition, proof, and primary action before decorative media", "Stack comparisons with their labels intact"], completionSignal: "A visitor can explain the offer, why to trust it, and what to do next." },
  { id: "application", name: "Application", purpose: "Support repeated work while preserving context, state, and efficient access to actions.", bestFor: ["Product workspaces", "Editors", "Operational tools"], regions: ["Global navigation", "Current location and task context", "Primary working surface", "Contextual controls", "Status and feedback"], mobileTransformation: ["Keep the working surface and primary action visible", "Collapse secondary navigation into an explicit disclosure"], completionSignal: "A user can complete the primary workflow and understand the resulting state." },
  { id: "onboarding", name: "Onboarding", purpose: "Guide a person through a small sequence of decisions with clear progress and recovery.", bestFor: ["Account setup", "First-run configuration", "Guided creation"], regions: ["Purpose and progress", "One primary decision", "Necessary explanation", "Primary and back actions", "Validation or confirmation"], mobileTransformation: ["Retain progress and the current question", "Keep actions reachable without obscuring fields"], completionSignal: "A person knows where they are, what is required, and what happens after continuing." },
  { id: "settings", name: "Settings", purpose: "Make configuration predictable, scannable, and safe to change.", bestFor: ["Preferences", "Account administration", "Permissions and integrations"], regions: ["Settings navigation", "Category title and scope", "Grouped controls", "Inline explanation and validation", "Save or persistence status"], mobileTransformation: ["Turn category navigation into an explicit back or selection pattern", "Stack labels and controls without separating help from its setting"], completionSignal: "A person can find a setting, understand its on-state, change it, and verify persistence." },
  { id: "editorial", name: "Editorial", purpose: "Lead a reader through a thesis, evidence, and conclusion at a deliberate pace.", bestFor: ["Reports", "Case studies", "Research explainers"], regions: ["Headline, deck, and provenance", "Thesis or summary", "Narrative sections", "Evidence and figures", "Methods, sources, or next reading"], mobileTransformation: ["Collapse columns while retaining narrative order", "Keep captions and sources attached to evidence"], completionSignal: "A reader can identify the thesis, supporting evidence, and provenance." },
  { id: "dashboard", name: "Dashboard", purpose: "Support monitoring and decisions by moving from takeaway to evidence to detail.", bestFor: ["Operations", "Analytics", "Experiment monitoring"], regions: ["Scope, freshness, and filters", "Decision-relevant summary", "Primary analytical view", "Supporting comparisons", "Exceptions and detail", "Methods and sources"], mobileTransformation: ["Stack by decision priority rather than desktop position", "Provide usable alternatives for wide charts and tables"], completionSignal: "A viewer can identify what changed, why it matters, and where to investigate." },
  { id: "collection", name: "Collection", purpose: "Help people scan, distinguish, select, and inspect a set of artifacts.", bestFor: ["Portfolios", "Archives", "Resource libraries"], regions: ["Collection identity and scope", "Search, filter, or navigation", "Featured item or collection grid", "Item identity and metadata", "Detail or next-item path"], mobileTransformation: ["Reduce columns based on minimum useful item width", "Expose metadata and actions without hover"], completionSignal: "A person can understand the collection, distinguish items, and inspect one in depth." },
  { id: "plan", name: "Plan or document", purpose: "Communicate an outcome, sequence, ownership, and next decisions without unnecessary application chrome.", bestFor: ["Project plans", "Proposals", "Decision documents"], regions: ["Title, status, and outcome", "Summary or decision", "Phases or sections", "Ownership, timing, and dependencies", "Risks or open questions", "Next action"], mobileTransformation: ["Keep outcome and current status first", "Stack timelines and responsibility fields without losing associations"], completionSignal: "A reader knows the intended outcome, sequence, owners, risks, and next action." }
];

export function findLayoutArchetype(id: string) { return layoutArchetypes.find(item => item.id === id); }
