import type { UiSkill } from "./ui-skills.js";

const style = (id: string, name: string, overview: string, guidance: string): UiSkill => ({ id, name, overview, guidance, source: "Postplan built-in style guide" });

export const styleSkills: UiSkill[] = [
  style("style-editorial-newspaper", "Style: editorial newspaper", "Information-dense, typographic storytelling with strong hierarchy and disciplined rules.", `Use a warm paper background (#f5f1e8), ink-black text (#1b1a18), and one muted signal color such as oxblood or cobalt. Build with a centered max-width, hairline rules, generous headline margins, narrow reading columns, pull quotes, captions, and occasional two-column sections.\n\nTypography: a high-contrast serif for display/headlines; a practical serif or sans-serif for body. Use sentence case, tight headline tracking, 1.5–1.7 body line-height, and a 60–70 character measure. Avoid cards, pills, gradients, and oversized rounded corners. Example: a research explainer, long-form case study, or release note.`),
  style("style-modern-product", "Style: modern product", "Clean, confident product presentation focused on clarity, actions, and generous spacing.", `Use a neutral canvas, near-black text, one vivid brand accent, and restrained surface elevation. Establish an 8px spacing scale. Use a single clear primary action and short, scannable sections. Prefer a 12-column desktop grid that collapses to one column on mobile.\n\nTypography: modern sans-serif, strong 600–700 weight headings, 16–18px body, compact labels. Cards should have a reason: grouping, status, or comparison. Keep radius and shadows consistent. Example: a SaaS landing page, settings area, or product onboarding flow.`),
  style("style-gallery", "Style: gallery / portfolio", "Image-led, spacious composition that gives artifacts room to be examined.", `Let content lead: large media areas, quiet labels, intentional cropping, and ample negative space. Use a masonry-like grid only when it improves scanning; otherwise use an even grid with consistent aspect ratios. Include captions with title, medium, date, and a concise description.\n\nUse a gallery-white, charcoal, or near-black backdrop and one subtle accent. Typography should be understated: a simple sans for metadata paired with a characterful display face only if it does not compete with work. Hover can reveal details, but all details must remain reachable by keyboard and touch. Example: photography, architecture, visual research, or a case-study archive.`),
  style("style-old-internet", "Style: old internet", "Deliberately handmade web energy: dense, personal, quirky, and legible rather than nostalgically unusable.", `Use saturated web-safe-inspired colors, patterned or tiled accents sparingly, visible borders, underlined links, and compact modules. Consider a fixed-width content well on desktop but preserve a fluid mobile layout. Make navigation explicit and text-first.\n\nTypography: system fonts, Verdana, Georgia, or a monospace utility face. Use small pixel-like details only for decoration, never for critical text. Add playful status badges, guestbook-like notes, or small GIF-style motifs only when they serve the concept. Do not imitate broken accessibility: preserve semantic HTML, contrast, focus states, and responsive reflow. Example: a personal homepage, fan archive, or playful learning tool.`),
  style("style-retro-futurist", "Style: retro futurist", "Optimistic science-fiction mood: bold geometry, luminous contrast, and controlled spectacle.", `Start from a deep navy or black field, then use one or two luminous accents—cyan, electric violet, acid lime, or solar orange. Build with thin grid lines, circular diagrams, chrome-like borders, and large geometric areas. Prefer CSS gradients and shapes over stock sci-fi imagery.\n\nTypography: a geometric sans or wide display face for titles; a highly legible sans/mono for body and data. Keep effects bounded: glow should mark hierarchy, not cover every component. Honor prefers-reduced-motion; animation should clarify data flow or response. Example: a technology explainer, data visualization, or future-facing concept page.`),
  style("style-quiet-minimal", "Style: quiet minimal", "Calm, reductionist design that foregrounds words and decisions through restraint.", `Use an off-white or near-black canvas, one text color, one low-saturation accent, ample whitespace, and almost no decorative surfaces. Establish a narrow content column and a clear vertical rhythm. Use dividers only to resolve ambiguity.\n\nTypography does the work: a refined serif or neutral sans, large but not theatrical headings, relaxed body leading, and limited weights. Avoid empty hero graphics, generic gradients, stacked cards, and tiny all-caps labels. Example: a focused plan, manifesto, documentation page, or reading experience.`),
  style("style-data-lab", "Style: data lab", "Analytical and structured: visual evidence, clear metrics, and technical credibility.", `Use a dark or pale neutral workspace with categorical colors reserved for data. Make units, time ranges, sources, and uncertainty visible. Lay out a summary row, then primary chart area, supporting views, and a methods/source section. Align numbers with tabular figures and avoid chart junk.\n\nTypography: compact sans for interface, monospace for values and code. Use cards as bounded analytical modules, with consistent padding and subtle borders. Every chart needs a title that states the takeaway, labeled axes where relevant, and an accessible text equivalent. Example: a model explainer, experiment report, operations dashboard, or research memo.`)
];
